name: clip_stack
description: "copy & paste: open-source, cross-platform, feature-rich."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ">=1.11.0"
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ">=3.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: roboto mono
      fonts:
        - asset: assets/fonts/roboto_mono.ttf
        - asset: assets/fonts/roboto_mono_italic.ttf
          style: italic
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard.ttf
